# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc


from . import serving_pb2 as serving__pb2


class HuichuanFlowServingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
            '/HuichuanFlow_serving.HuichuanFlowServing/Predict',
            request_serializer=serving__pb2.PredictReq.SerializeToString,
            response_deserializer=serving__pb2.PredictResp.FromString,
        )


class HuichuanFlowServingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HuichuanFlowServingServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Predict': grpc.unary_unary_rpc_method_handler(
            servicer.Predict,
            request_deserializer=serving__pb2.PredictReq.FromString,
            response_serializer=serving__pb2.PredictResp.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'HuichuanFlow_serving.HuichuanFlowServing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class HuichuanFlowServing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HuichuanFlow_serving.HuichuanFlowServing/Predict',
                                             serving__pb2.PredictReq.SerializeToString,
                                             serving__pb2.PredictResp.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
