# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serving.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serving.proto',
  package='HuichuanFlow.serving',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rserving.proto\x12\x14HuichuanFlow.serving\"$\n\x06Matrix\x12\r\n\x05value\x18\x01 \x03(\x02\x12\x0b\n\x03\x64im\x18\x02 \x03(\x05\"8\n\nPredictReq\x12*\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1c.HuichuanFlow.serving.Matrix\"9\n\x0bPredictResp\x12*\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1c.HuichuanFlow.serving.Matrix2e\n\x11MatrixSlowServing\x12P\n\x07Predict\x12 .HuichuanFlow.serving.PredictReq\x1a!.HuichuanFlow.serving.PredictResp\"\x00\x62\x06proto3'
)




_MATRIX = _descriptor.Descriptor(
  name='Matrix',
  full_name='HuichuanFlow.serving.Matrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='HuichuanFlow.serving.Matrix.value', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dim', full_name='HuichuanFlow.serving.Matrix.dim', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=75,
)


_PREDICTREQ = _descriptor.Descriptor(
  name='PredictReq',
  full_name='HuichuanFlow.serving.PredictReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='HuichuanFlow.serving.PredictReq.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=133,
)


_PREDICTRESP = _descriptor.Descriptor(
  name='PredictResp',
  full_name='HuichuanFlow.serving.PredictResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='HuichuanFlow.serving.PredictResp.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=192,
)

_PREDICTREQ.fields_by_name['data'].message_type = _MATRIX
_PREDICTRESP.fields_by_name['data'].message_type = _MATRIX
DESCRIPTOR.message_types_by_name['Matrix'] = _MATRIX
DESCRIPTOR.message_types_by_name['PredictReq'] = _PREDICTREQ
DESCRIPTOR.message_types_by_name['PredictResp'] = _PREDICTRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Matrix = _reflection.GeneratedProtocolMessageType('Matrix', (_message.Message,), {
  'DESCRIPTOR' : _MATRIX,
  '__module__' : 'serving_pb2'
  # @@protoc_insertion_point(class_scope:HuichuanFlow.serving.Matrix)
  })
_sym_db.RegisterMessage(Matrix)

PredictReq = _reflection.GeneratedProtocolMessageType('PredictReq', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTREQ,
  '__module__' : 'serving_pb2'
  # @@protoc_insertion_point(class_scope:HuichuanFlow.serving.PredictReq)
  })
_sym_db.RegisterMessage(PredictReq)

PredictResp = _reflection.GeneratedProtocolMessageType('PredictResp', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTRESP,
  '__module__' : 'serving_pb2'
  # @@protoc_insertion_point(class_scope:HuichuanFlow.serving.PredictResp)
  })
_sym_db.RegisterMessage(PredictResp)



_MATRIXSLOWSERVING = _descriptor.ServiceDescriptor(
  name='MatrixSlowServing',
  full_name='HuichuanFlow.serving.MatrixSlowServing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=194,
  serialized_end=295,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='HuichuanFlow.serving.MatrixSlowServing.Predict',
    index=0,
    containing_service=None,
    input_type=_PREDICTREQ,
    output_type=_PREDICTRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATRIXSLOWSERVING)

DESCRIPTOR.services_by_name['MatrixSlowServing'] = _MATRIXSLOWSERVING

# @@protoc_insertion_point(module_scope)
